repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v1.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements
  - id: flake8
    args:
      - --max-line-length=160
      - --exclude=*/migrations/*,docs/*
      - --ignore=E126
  - id: check-added-large-files
  - id: requirements-txt-fixer
    args:
      - requirements.txt
      - requirements-dev.txt
- repo: git://github.com/ambv/black
  rev: 18.4a2
  hooks:
    - id: black
      args: [--line-length=160, --safe]
